### ISSUE TITLE
MDT For Typecho

### ISSUE THREAD

**Issue by ocoke** [oCoke/MDT-For-Typecho#1]
https://www.hifun.site/project/mdt-typecho/issues/

**Comment by oCoke** [comment]
Hi! @r233r

**Comment by oCoke** [comment]
better

**Comment by ocoke** [comment]
`MDT For Typehcho` 的第 1 个预览版本应该会在下周左右发布 吧。

**Comment by oCoke** [comment]
- [x] AppBar
- [x] SideBar
- [x] 重写评论
- [ ] 归档页面
- [ ] 友链页面
- [x] 顺滑滚动
- [x] 重写首页
- [ ] Ajax 评论*
- [ ] 全站 Pjax*
- [ ] 图片懒加载
- [x] 代码高亮 (highlight.js)
- [ ] 分割中英文 (Pangu.js)
- [ ] 站点静态资源 CDN 设置
- [x] 重写文章页面
- [ ] 侧边栏站点简介

**Comment by ocoke** [comment]
新增图片懒加载，顺滑滚动等功能。

**Comment by oCoke** [comment]
![](https://hi.hifun.site/image/2020/10/20/854c21f670f90.gif)

**Comment by ocoke** [comment]
今天准备咕咕咕~

**Comment by ocoke** [comment]
居然没咕，但是功能还是比较少。会持续优化的。
