### ISSUE TITLE
移动端无法正常打开 RSS 菜单

### ISSUE THREAD

**Issue by r233r** [oCoke/MDT-For-Typecho#2]
## 遇到的问题

移动端点击「RSS」的按键，会同时打开侧边栏，无法选择文章 RSS 与评论 RSS

## 运行环境

Typecho 1.1 稳定版，MDT(Beta-V0.3)

## 图片
![演示站点](https://user-images.githubusercontent.com/67464863/97773372-1d8abb00-1b8a-11eb-941a-8473c6966b85.gif)

**Comment by ocoke** [comment]
将在下一个版本中修复。感谢您的反馈！

**Comment by r233r** [comment]
## 图片
![演示站点](https://user-images.githubusercontent.com/67464863/97773372-1d8abb00-1b8a-11eb-941a-8473c6966b85.gif)

**Comment by ocoke** [comment]
当前问题已在最新的`dev`分支修改中修复：https://github.com/oCoke/MDT-For-Typecho/commit/4674b3d9622f69abed74df6560bdb7e630fa4790

**Comment by oCoke** [comment]
已解决！

**Comment by ocoke** [comment]
已解决！
